= {lab_name}

Welcome to our workshop!

Please, follow the instructions below to execute the workshop, and in case you have questions, always remember that the instructors are here to help. If you have problems with your lab or just have technical questions, feel free to reach out.


== Requirements

For this workshop you will be provided access to an OpenShift cluster and development tools to build and deploy integration using Red Hat build of Apache Camel. To utilize these resources you only need a browser and internet connection.

For browsers, we recommend the use of Google Chrome or Mozzilla Firefox.

== Lab Modules

This workshop contains 4 modules. For the complete experience, these modules were made to be executed from 1 to 4, but since we recognize that we have attendees interested in different aspects of an integration lifecycle, you can skip modules and use provided scripts to execute the previous steps for you. Independetly of how you decide to execute this workshop, we recommend that you, at least, go throught the first module to get familirized with the tools used in this workshop. 

=== Getting Started with the Workshop

In this module you will get introduced to the environment and tools used in this workshop. You will also create and deploy a *hello-world* integration.

=== Developing Integrations with Camel

For this module you'll actually implement and deploy integrations. You will have access to a mock system called Globex, an e-commerce solution for Red Hat's swags. This system has a CDC(Change Data Capture) implementation to capture order and calculate cashback. The module requires you to implement the missing pieces to make the cashback implementation to work and build a REST API interface to interact with the cashback system database.

=== Monitoring Integrations in OpenShift

This module is focused on how you can monitor your integrations using Hawtio and Prometheus. Instead of creating new Routes, you will redeploy the ones created on module 2, but this time you will add *traits* to enable Hawtio and Prometheus.

=== Automate your deploying with Tekton

In the previous module you used developer tools to deploy Integrations. Although it was really easy and fast to deploy that way, that approach only works for development. In a real life scenario we need to integrate the development with source code management and automate the deployment process. In this module you will learn how to use Tekton pipelines to deploy different styles of Camel projects.